services:
    postgres:
        image: postgres:17.2-alpine
        environment:
            POSTGRES_USER: digimon
            POSTGRES_PASSWORD: digimon
            POSTGRES_DB: digimon
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digimon
            SPRING_DATASOURCE_USERNAME: digimon
            SPRING_DATASOURCE_PASSWORD: digimon
        ports:
            - "8081:8081"
        depends_on:
            - postgres