## Server properties ##
server:
    port: 8081

## Spring properties ##
spring:
    mvc:
        servlet:
            path: /api
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/digimon
        username: digimon
        password: digimon
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true